#!/bin/sh

set -eu

# Minimal mock for "ubus call network.interface.<iface> status".

if [ "$1" != "call" ] || [ -z "${2:-}" ] || [ "${3:-}" != "status" ]; then
	exit 1
fi

cat <<JSON
{"ipv4-address":[{"address":"${MOCK_IP_OVERRIDE:-1.2.3.4}"}]}
JSON
