#!/bin/sh

set -eu

# Minimal mock for "uci -q get" used by aliddns.sh.

if [ "$#" -lt 3 ] || [ "$1" != "-q" ] || [ "$2" != "get" ]; then
	exit 1
fi

key="$3"
case "$key" in
	aliddns.main.enabled)
		echo "1";;
	aliddns.main.access_key_id)
		echo "${MOCK_ACCESS_KEY_ID:-}";;
	aliddns.main.access_key_secret)
		echo "${MOCK_ACCESS_KEY_SECRET:-}";;
	aliddns.main.domain)
		echo "${MOCK_DOMAIN:-}";;
	aliddns.main.rr)
		echo "${MOCK_RR:-@}";;
	aliddns.main.type)
		echo "${MOCK_TYPE:-A}";;
	aliddns.main.ttl)
		echo "${MOCK_TTL:-600}";;
	aliddns.main.ip_source)
		echo "${MOCK_IP_SOURCE:-wan}";;
	aliddns.main.ip_override)
		echo "${MOCK_IP_OVERRIDE:-}";;
	aliddns.main.interval)
		echo "${MOCK_INTERVAL:-300}";;
	aliddns.main.log_path)
		echo "${MOCK_LOG_PATH:-}";;
	aliddns.main.api_endpoint)
		echo "${MOCK_API_ENDPOINT:-https://alidns.aliyuncs.com/}";;
	aliddns.main.api_version)
		echo "${MOCK_API_VERSION:-2015-01-09}";;
	aliddns.main.mode)
		echo "${MOCK_MODE:-sync}";;
	aliddns.main.record_id)
		echo "${MOCK_RECORD_ID:-}";;
	aliddns.main.value)
		echo "${MOCK_VALUE:-}";;
	aliddns.main.page_size)
		echo "${MOCK_PAGE_SIZE:-100}";;
	aliddns.main.list_rr)
		echo "${MOCK_LIST_RR:-}";;
	aliddns.main.list_type)
		echo "${MOCK_LIST_TYPE:-}";;
	*)
		exit 1;;
esac
