#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/aliddns.sh --daemon
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	return 0
}
